language: node_js

node_js:
  - 'stable'

cache:
  directories:
    - node_modules

script:
  - npm run format
  - npm run lint
  - npm run test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  repo: mehamasum/mehamasum.github.io
  target-branch: master
  local-dir: public
